branch-defaults:
  redesign:
    environment: kingclothing-env
global:
  application_name: kingclothing
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.3.0 running Ruby 2.1 (Puma)
  default_region: eu-west-1
  profile: eb-cli
  sc: git
