this._=this._||{};(function(_){var window=this;
try{
var ra,sa;_.q=function(a){return function(){return _.ba[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.ba=[];_.ea=_.ea||{};_.r=this;_.fa=function(a){return void 0!==a};
_.ja=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.ka=function(a){return"array"==_.ja(a)};_.la=function(a){return"string"==typeof a};_.na="closure_uid_"+(1E9*Math.random()>>>0);ra=function(a,b,c){return a.call.apply(a.bind,arguments)};
sa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.t=function(a,b,c){_.t=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ra:sa;return _.t.apply(null,arguments)};
_.ua=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.va=Date.now||function(){return+new Date};_.u=function(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.iu=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
_.wa=window.gadgets||{};_.Ba=window.osapi=window.osapi||{};_.google=window.google||{};
}catch(e){_._DumpException(e)}
try{
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:!1,rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

}catch(e){_._DumpException(e)}
try{
_.Ca=function(a,b){return b};_.B=function(a,b){var c=a.split("."),d=_.r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.fa(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.D=function(a,b){b=_.Ca(a,b);_.B(a,b)};_.Da=window;_.Ea=window.document;_.Fa=_.Da.location;_.Ga=/\[native code\]/;_.Ha=function(a,b,c){return a[b]=a[b]||c};_.Ka=function(){var a;if((a=Object.create)&&_.Ga.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a}; _.Ma=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Pa=function(a,b){a=a||{};for(var c in a)_.Ma(a,c)&&(b[c]=a[c])};_.Ra=function(a,b){if(!a)throw Error(b||"");};_.Sa=_.Ha(_.Da,"gapi",{});
_.Xa=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.$a=function(a,b,c){_.Ya(a,b,c,"add","at")};_.Ya=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.bb=_.Ha(_.Da,"___jsl",_.Ka());_.Ha(_.bb,"I",0);_.Ha(_.bb,"hel",10);var cb,db,eb,fb,gb,hb;cb=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};db=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};eb=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};fb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!eb(a[c])&&!eb(b[c])?fb(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=eb(b[c])?[]:{},fb(a[c],b[c])):a[c]=b[c])};
gb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(d){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(e){}return"object"===typeof b?b:{}}};
hb=function(a){db(!0);var b=window.___gcfg,c=cb("cu");if(b&&b!==window.___gu){var d={};fb(d,b);c.push(d);window.___gu=b}var b=cb("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,cb("us"));for(var g=0;g<e.length;++g)for(var k=e[g],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(g=f.nodeType,f=3==g||4==g?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=gb(f))&&b.push(f));a&&(d={},fb(d,a),c.push(d));d=cb("cd");a=0;for(b=d.length;a<b;++a)fb(db(),d[a]);d=cb("ci");a=0;for(b=d.length;a<b;++a)fb(db(),d[a]);a=0;for(b=c.length;a<b;++a)fb(db(),c[a])};_.E=function(a,b){if(!a)return db();for(var c=a.split("/"),d=db(),e=0,f=c.length;d&&"object"===typeof d&&e<f;++e)d=d[c[e]];return e===c.length&&void 0!==d?d:b}; _.ib=function(a,b){var c=a;if("string"===typeof a){for(var d=c={},e=a.split("/"),f=0,g=e.length;f<g-1;++f)var k={},d=d[e[f]]=k;d[e[f]]=b}hb(c)};
var jb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Ha(_.bb,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};jb&&jb();hb();_.D("gapi.config.get",_.E);_.D("gapi.config.update",_.ib);
}catch(e){_._DumpException(e)}
try{
var nb,ob,qb,rb,sb,tb,vb,wb,yb,Ab,Bb,Db,Hb,Ib,Lb;_.kb=function(a){return!!a&&"object"===typeof a&&_.Ga.test(a.push)};_.lb=function(a,b,c){if(a){_.Ra(_.kb(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};_.mb=function(a,b,c){if(a)if(_.kb(a))_.lb(a,b,c);else{_.Ra("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)_.Ma(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};
nb=function(a){a=a.sort();for(var b=[],c=void 0,d=0;d<a.length;d++){var e=a[d];e!=c&&b.push(e);c=e}return b};ob=function(){var a=[],b=_.bb.H;b&&_.mb(b,function(b){a.push.apply(a,b.L)});return nb(a)};_.pb=function(a){if(_.Ga.test(Object.keys))return Object.keys(a);var b=[],c;for(c in a)_.Ma(a,c)&&b.push(c);return b};wb={};yb=0;Ab=_.Ka();Bb=_.Ka();Db=function(a){return"number"===typeof a&&a>Math.random()};
_.Eb=function(a){if("undefined"===typeof qb){var b=_.E("report")||{},c=b.rate;Math.random();tb=b.timeout||1E3;rb=b.host||"https://plus.google.com";sb=b.path||"/_/widget/report";qb=[];Db(c)&&(qb=b.apis||[]);var b=b.apiRate||{},d;for(d in b)Db(b[d])&&qb.push(d)}for(d=0;d<qb.length;++d)if((new RegExp("^"+qb[d]+"$")).test(a))return!0;return!1};Hb=function(a){delete wb[a]};
Ib=function(){vb&&(_.Da.clearTimeout(vb),vb=0);vb=_.Da.setTimeout(function(){var a;a=window.document.location;a=a.protocol+"//"+a.host+a.pathname;var b=_.pb(Bb).join(":");a=[rb,sb,"?api=",(0,window.encodeURIComponent)(b),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(ob().join(":"))].join("");Bb=_.Ka();var b=new window.Image,c=yb++;wb[c]=b;b.onload=b.onerror=_.ua(Hb,c);b.src=a;vb=0},tb)};_.Kb=function(a){Ab[a]||(Bb[a]=!0,Ab[a]=!0,Ib())};Lb=_.Ca; _.Ca=function(a,b){var c=Lb(a,b);"function"===typeof b&&_.Eb(a)&&(c=function(c){_.Kb(a);return b.apply(this,arguments)});return c};

}catch(e){_._DumpException(e)}
try{
_.hj=window.gapi&&window.gapi.util||{};
}catch(e){_._DumpException(e)}
try{
var ij=_.hj=_.hj||{};window.___jsl=window.___jsl||{};ij.oo={A:function(){return window.___jsl.bsh},yv:function(){return window.___jsl.h},Cr:function(a){window.___jsl.bsh=a},vK:function(a){window.___jsl.h=a}};
}catch(e){_._DumpException(e)}
try{
var lj,mj;lj=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/u\/(\d)\//;mj=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/b\/(\d{10,})\//;_.nj=function(a){var b=_.E("googleapis.config/sessionIndex");null==b&&(b=window.__X_GOOG_AUTHUSER);if(null==b){var c=window.google;c&&(b=c.authuser)}null==b&&(a=a||window.location.href,b=_.Xa(a,"authuser")||null,null==b&&(b=(b=a.match(lj))?b[1]:null));return null==b?null:String(b)};
_.oj=function(a){var b=_.E("googleapis.config/sessionDelegate");null==b&&(b=(a=(a||window.location.href).match(mj))?a[1]:null);return null==b?null:String(b)};_.pj=function(a,b){var c=_.nj(a)||b,d=_.oj(a),e="";c&&(e+="u/"+c+"/");d&&(e+="b/"+d+"/");return e||null};

}catch(e){_._DumpException(e)}
try{
_.qj=function(a){var b;if(b=_.E("enableMultilogin"))if(b=a("cookie_policy"))b=String(a("immediate")||""),a=String(a("prompt")||""),b=!("true"===b.toLowerCase()||"none"===a.toLowerCase());return b?!0:!1};
_.rj=function(a,b,c){a=String(a);if(null!=(_.Xa(a,"authuser")||null)||null!=(_.Xa(a,"hd")||null))return a;b=_.nj(b);if(c){var d=a,e=d.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(e&&e[0]){var f=e[1],g=e[4],k=e[5];e[3]=="/"+c&&(d=(f||"")+(g||"/")+(k||""))}if((e=d.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&e[0]){var f=e[2],l=e[4]||e[5],k=e[6];null!=b&&(d=(f||"")+"/"+c+"/"+(0,window.encodeURIComponent)(b)+(l||"/")+(k||""));return d}}null==
b?_.qj(function(b){return _.Xa(a,b)||null})||(l=(0,window.encodeURIComponent)("authuser")+"=0"):l=b.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)(String(b)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(b)].join(""):["authuser=",(0,window.encodeURIComponent)(b)].join("");c=a.split("#");b=c[0].indexOf("?");0>b?c[0]=[c[0],"?",l].join(""):(d=[c[0]],b<c[0].length-1&&d.push("&"),d.push(l),c[0]=d.join("")); return d=c.join("#")};_.google.UU=_.rj;_.google.Hp=_.nj;_.google.nU=_.oj;_.google.oU=_.pj;

}catch(e){_._DumpException(e)}
try{
_.sj=function(){this.B=-1};
}catch(e){_._DumpException(e)}
try{
var tj=function(){this.B=-1;this.B=64;this.A=[];this.I=[];this.G=[];this.D=[];this.D[0]=128;for(var a=1;a<this.B;++a)this.D[a]=0;this.F=this.C=0;this.reset()};_.u(tj,_.sj);tj.prototype.reset=function(){this.A[0]=1732584193;this.A[1]=4023233417;this.A[2]=2562383102;this.A[3]=271733878;this.A[4]=3285377520;this.F=this.C=0};
var uj=function(a,b,c){c||(c=0);var d=a.G;if(_.la(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.A[0];c=a.A[1];for(var g=a.A[2],k=a.A[3],l=a.A[4],m,e=0;80>e;e++)40>e?20>e?(f=k^c&(g^k),m=1518500249):(f=c^g^k,m=1859775393):60>e?(f=c&g|k&(c|g),m=2400959708):(f=c^g^k,m=3395469782),
f=(b<<5|b>>>27)+f+l+m+d[e]&4294967295,l=k,k=g,g=(c<<30|c>>>2)&4294967295,c=b,b=f;a.A[0]=a.A[0]+b&4294967295;a.A[1]=a.A[1]+c&4294967295;a.A[2]=a.A[2]+g&4294967295;a.A[3]=a.A[3]+k&4294967295;a.A[4]=a.A[4]+l&4294967295};
tj.prototype.update=function(a,b){if(null!=a){_.fa(b)||(b=a.length);for(var c=b-this.B,d=0,e=this.I,f=this.C;d<b;){if(0==f)for(;d<=c;)uj(this,a,d),d+=this.B;if(_.la(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.B){uj(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.B){uj(this,e);f=0;break}}this.C=f;this.F+=b}};
tj.prototype.digest=function(){var a=[],b=8*this.F;56>this.C?this.update(this.D,56-this.C):this.update(this.D,this.B-(this.C-56));for(var c=this.B-1;56<=c;c--)this.I[c]=b&255,b/=256;uj(this,this.I);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.A[c]>>d&255,++b;return a};
_.vj=function(){this.vi=new tj};_.h=_.vj.prototype;_.h.reset=function(){this.vi.reset()};_.h.kA=function(a){this.vi.update(a)};_.h.Ku=function(){return this.vi.digest()};_.h.ls=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.kA(b)};_.h.xe=function(){for(var a=this.Ku(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

}catch(e){_._DumpException(e)}
try{
var Kl,Jl,Ql,Rl,Ll,Ol,Ml,Sl,Nl,Jl;_.Pl=function(){var a;Jl?(a=new _.Da.Uint32Array(1),Kl.getRandomValues(a),a=Number("0."+a[0])):(a=Ll,a+=(0,window.parseInt)(Ml.substr(0,20),16),Ml=Nl(Ml),a=a/(Ol+Math.pow(16,20)));return a};Kl=_.Da.crypto;Jl=!1;Ql=0;Rl=0;Ll=1;Ol=0;Ml="";Sl=function(a){a=a||_.Da.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;Ll=Ll*b%Ol;0<Ql&&++Rl==Ql&&_.Ya(_.Da,"mousemove",Sl,"remove","de")};Nl=function(a){var b=new _.vj;b.ls(a);return b.xe()};
Jl=!!Kl&&"function"==typeof Kl.getRandomValues;Jl||(Ol=1E6*(window.screen.width*window.screen.width+window.screen.height),Ml=Nl(_.Ea.cookie+"|"+_.Ea.location+"|"+(new Date).getTime()+"|"+Math.random()),Ql=_.E("random/maxObserveMousemove")||0,0!=Ql&&_.$a(_.Da,"mousemove",Sl));

}catch(e){_._DumpException(e)}
try{
var Tl,Vl,Wl,Xl,Yl,Zl,$l,am,bm,cm,fm,gm,hm,im,jm,km;Tl=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.Ul=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;Vl=function(a,b){var c=[];if(a)for(var d in a)if(_.Ma(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};Wl=function(a){return a.iu+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.Bl.length?"#"+a.Bl.join("&"):"")};
Xl=function(a){a=a.match(Tl);var b=_.Ka();b.iu=a[1];b.query=a[3]?[a[3]]:[];b.Bl=a[5]?[a[5]]:[];return b};Yl=/'/g;Zl=/"/g;$l=/>/g;am=/</g;bm=/&/g;cm=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.dm=function(a,b){var c="";2E3<b.length&&(c=b.substring(2E3),b=b.substring(0,2E3));var d=a.createElement("div"),e=a.createElement("a");e.href=b;d.appendChild(e);d.innerHTML=d.innerHTML;b=String(d.firstChild.href);d.parentNode&&d.parentNode.removeChild(d);return b+c};
_.em=function(a,b,c,d){a=Xl(a);a.query.push.apply(a.query,Vl(b,d));a.Bl.push.apply(a.Bl,Vl(c,d));return Wl(a)};fm=function(a){return String(a).replace(bm,"&amp;").replace(am,"&lt;").replace($l,"&gt;").replace(Zl,"&quot;").replace(Yl,"&#39;")};hm=function(){var a=_.bb.onl;if(!a){a=_.Ka();_.bb.onl=a;var b=_.Ka();a.e=function(a){var d=b[a];d&&(delete b[a],d())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a}; im=function(a,b){var c=b.onload;return"function"===typeof c?(hm().a(a,c),c):null};jm=function(a){_.Ra(/^\w+$/.test(a),"Unsupported id - "+a);hm();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};km=function(a){hm().r(a)};
var mm,nm,rm;_.lm={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};mm={allowtransparency:!0,onload:!0};nm=0;_.om=function(a,b){var c,d=0;do c=b.id||["I",nm++,"_",(new Date).getTime()].join("");while(a.getElementById(c)&&5>++d);_.Ra(5>d,"Error creating iframe id");return c};_.pm=function(a,b){return a?b+"/"+a:""};
_.qm=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);_.Pa(d.queryParams||{},e);_.Pa(d.fragmentParams||{},f);var g=d.connectWithQueryParams?e:f,k=d.pfname,l=_.Ka();l.id=c;l.parent=a.location.protocol+"//"+a.location.host;c=_.Xa(a.location.href,"parent");k=k||"";!k&&c&&(k=_.pm(_.Xa(a.location.href,"id",""),_.Xa(a.location.href,"pfname","")));l.pfname=k;_.Pa(l,g);(l=_.Xa(b,"rpctoken")||e.rpctoken||f.rpctoken)||(l=g.rpctoken=d.rpctoken||String(Math.round(1E8*
_.Pl())));d.rpctoken=l;g=a.location.href;a=_.Ka();(l=_.Xa(g,"_bsh",_.bb.bsh))&&(a._bsh=l);(g=_.bb.dpo?_.bb.h:_.Xa(g,"jsh",_.bb.h))&&(a.jsh=g);d.hintInFragment?_.Pa(a,f):_.Pa(a,e);return _.em(b,e,f,d.paramsSerializer)};rm=function(a){_.Ra(!a||_.Ul.test(a),"Illegal url for new iframe - "+a)};
_.sm=function(a,b,c,d,e){rm(c.src);var f,g=im(d,c),k=g?jm(d):"";try{window.document.all&&(f=a.createElement('<iframe frameborder="'+fm(String(c.frameborder))+'" scrolling="'+fm(String(c.scrolling))+'" '+k+' name="'+fm(String(c.name))+'"/>'))}catch(l){}finally{f||(f=a.createElement("iframe"),g&&(f.onload=function(){f.onload=null;g.call(this)},km(d)))}for(var m in c)a=c[m],"style"===m&&"object"===typeof a?_.Pa(a,f.style):mm[m]||f.setAttribute(m,String(a));(m=e&&e.beforeNode||null)||e&&e.dontclear|| cm(b);b.insertBefore(f,m);f=m?m.previousSibling:b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var tm,wm;tm=/^:[\w]+$/;_.um=/:([a-zA-Z_]+):/g;_.vm=function(){var a=_.nj()||"0",b=_.oj(),c=_.pj(void 0,a),d=!1===_.E("isLoggedIn"),e=d?"_/im/":"";e&&(c="");var f=_.E("iframes/:socialhost:"),g=_.E("iframes/:im_socialhost:");return gm={socialhost:f,ctx_socialhost:d?g:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};wm=function(a,b){return _.vm()[b]||""};_.xm=function(a){return _.dm(_.Ea,a.replace(_.um,wm))};
_.ym=function(a){var b=a;tm.test(a)&&(b=_.E("iframes/"+b.substring(1)+"/url"),_.Ra(!!b,"Unknown iframe url config for - "+a));return _.xm(b)};
_.zm=function(a,b,c){var d=c||{};c=d.attributes||{};_.Ra(!d.allowPost||!c.onload,"onload is not supported by post iframe");a=_.ym(a);c=b.ownerDocument||_.Ea;var e=_.om(c,d);a=_.qm(c,a,e,d);var f=_.Ka();_.Pa(_.lm,f);_.Pa(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;if((d||{}).allowPost&&2E3<a.length){var g=Xl(a);f.src="";f["data-postorigin"]=a;a=_.sm(c,b,f,e);var k;if(-1!=window.navigator.userAgent.indexOf("WebKit")){k=a.contentWindow.document;k.open();var f=k.createElement("div"),l={},m=e+"_inner";
l.name=m;l.src="";l.style="display:none";_.sm(c,f,l,m,d)}f=(d=g.query[0])?d.split("&"):[];d=[];for(l=0;l<f.length;l++)m=f[l].split("=",2),d.push([(0,window.decodeURIComponent)(m[0]),(0,window.decodeURIComponent)(m[1])]);g.query=[];f=Wl(g);_.Ra(_.Ul.test(f),"Invalid URL: "+f);g=c.createElement("form");g.action=f;g.method="POST";g.target=e;g.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type="hidden",f.name=d[e][0],f.value=d[e][1],g.appendChild(f);b.appendChild(g);g.submit(); g.parentNode.removeChild(g);k&&k.close();b=a}else b=_.sm(c,b,f,e,d);return b};

}catch(e){_._DumpException(e)}
try{
_.jj=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!== e)c=":"+e}return a+"://"+b+c};

}catch(e){_._DumpException(e)}
try{
_.hj.Aa=function(a){return _.jj(a)};
}catch(e){_._DumpException(e)}
try{
_.I=_.I||{};
}catch(e){_._DumpException(e)}
try{
_.I=_.I||{};_.I.Dm=function(a,b,c){for(var d=[],e=2,f=arguments.length;e<f;++e)d.push(arguments[e]);return function(){for(var c=d.slice(),e=0,f=arguments.length;e<f;++e)c.push(arguments[e]);return b.apply(a,c)}};_.I.Yj=function(a){var b,c,d={};for(b=0;c=a[b];++b)d[c]=c;return d};

}catch(e){_._DumpException(e)}
try{
_.I=_.I||{};
(function(){function a(a,b){return String.fromCharCode(b)}var b={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.I.escape=function(a,b){if(a){if("string"===typeof a)return _.I.wl(a);if("Array"===typeof a)for(var e=0,f=a.length;e<f;++e)a[e]=_.I.escape(a[e]);else if("object"===typeof a&&b){e={};for(f in a)a.hasOwnProperty(f)&&(e[_.I.wl(f)]=_.I.escape(a[f],!0));return e}}return a};_.I.wl=function(a){if(!a)return a;for(var d=[],e,f,g=0,k= a.length;g<k;++g)e=a.charCodeAt(g),f=b[e],!0===f?d.push("&#",e,";"):!1!==f&&d.push(a.charAt(g));return d.join("")};_.I.AV=function(b){return b?b.replace(/&#([0-9]+);/g,a):b}})();

}catch(e){_._DumpException(e)}
try{
_.Il=_.Il||{};_.Il.fG=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

}catch(e){_._DumpException(e)}
try{
_.Il=_.Il||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.Il.Cb=function(){var b=_.Il.fG().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift(),d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight)var g=f.offsetTop+f.offsetHeight+a(f,"margin-bottom"),b=Math.max(b,g);c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

}catch(e){_._DumpException(e)}
try{
_.Pb=function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(g){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Nb=function(b){a(2,b)};_.Mb=function(b){a(3,b)};_.Ob=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b}();

}catch(e){_._DumpException(e)}
try{
_.I=_.I||{};(function(){var a=[];_.I.YU=function(b){a.push(b)};_.I.lV=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
}catch(e){_._DumpException(e)}
try{
_.Qb=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.Sb=function(a,b){var c=_.Ha(_.bb,"watt",_.Ka());_.Ha(c,a,b)};_.I=_.I||{};
(function(){var a=null;_.I.qb=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,g=b.length;f<g;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.I.qb()})();
_.D("gadgets.util.getUrlParameters",_.I.qb);
}catch(e){_._DumpException(e)}
try{
_.Tb=window.console;_.Ub=function(a){_.Tb&&_.Tb.log&&_.Tb.log(a)};_.Vb=function(){};
}catch(e){_._DumpException(e)}
try{
_.Wb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.ib(a());return{register:function(a,c,d){d&&d(_.E())},get:function(a){return _.E(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.ib(a)},Xa:function(){}}}();
_.D("gadgets.config.register",_.Wb.register);_.D("gadgets.config.get",_.Wb.get);_.D("gadgets.config.init",_.Wb.Xa);_.D("gadgets.config.update",_.Wb.update);
}catch(e){_._DumpException(e)}
try{
var Xb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},Yb=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=Xb[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";b=[];if("number"===
typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(Yb(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.Ma(a,c)&&"string"===typeof c&&(d=Yb(a[c]))&&b.push(Yb(c)+":"+d);return"{"+b.join(",")+"}"}return""}},Zb=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}return!1}, $b=!1,bc;try{$b=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(ac){}bc=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.dc=$b?window.JSON.stringify:Yb;_.ec=$b?bc:Zb;

}catch(e){_._DumpException(e)}
try{
_.D("gadgets.json.stringify",_.dc);_.D("gadgets.json.parse",_.ec);_.Xa(_.Da.location.href,"rpctoken")&&_.$a(_.Ea,"unload",function(){});
}catch(e){_._DumpException(e)}
try{
var fc,ic;fc=function(){var a=_.Ea.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.gc=function(a){if(fc())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Da.addEventListener?(_.Da.addEventListener("load",c,!1),_.Da.addEventListener("DOMContentLoaded",c,!1)):_.Da.attachEvent&&(_.Da.attachEvent("onreadystatechange",function(){fc()&&c.apply(this,arguments)}),_.Da.attachEvent("onload",c))}};_.hc=function(a,b){if(!fc())try{a()}catch(c){}_.gc(b)}; ic=ic||{};ic.Ty=null;ic.Dx=null;ic.lm=null;ic.frameElement=null;
ic=ic||{};
ic.xs||(ic.xs=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.ec)(a.data);if(b&&b.f){(0,_.Ob)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.K.Ff(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Mb("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{Bh:function(){return"wpm"},A:function(){return!0},Xa:function(f,g){_.Wb.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=g;a(b);d("..",!0);return!0},kb:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.K.Ff(a),e=_.K.Xt(a);d?window.setTimeout(function(){var a=(0,_.dc)(c);(0,_.Ob)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Mb("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
ic=ic||{};
ic.Al||(ic.Al=function(){function a(a,b){H[b]=H[b]||function(){a.apply({},arguments)}}function b(){if(null===v&&window.document.body&&l){var a=l+"?cb="+Math.random()+"&origin="+A+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="___xpcswf" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;v=c.firstChild}++x;null!==w&&(null!==v||50<=x)?window.clearTimeout(w):w=window.setTimeout(b,100)}function c(){G[".."]||(k(".."),y++,50<=y&&null!==C?(window.clearTimeout(C),C=null):C=window.setTimeout(c,100))}function d(){if(null!==v&&v.setup)for(;0<z.length;){var a=z.shift(),b=a.ZK;v.setup(a.xi,".."===b?_.K.Tn:b,".."===b?"INNER":"OUTER")}null!==w&&window.clearTimeout(w);w=null}function e(){G[".."]||null!==
C||(C=window.setTimeout(c,100))}function f(a,b,c){b=_.K.Ff(a);var d=_.K.og(a);v["sendMessage_"+(".."===a?_.K.Tn:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(v,(0,_.dc)(c),b);return!0}function g(a,b){var c=(0,_.ec)(a),d=c._scr;d?(p(d,!0),G[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){n(c,b)},0)}function k(a,b){var c=_.K.Tn,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l=null,m=!1,n=null,p=null,v=null,z=[],w=null,x=0,y=0,C=null,G={},A=window.location.protocol+"//"+window.location.host,H;window.___jsl=
window.___jsl||{};H=window.___jsl._fm={};_.Wb.register("rpc",null,function(a){m&&(l=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(g,"receiveMessage");return{Bh:function(){return"flash"},A:function(){return!0},Xa:function(a,b){n=a;p=b;return m=!0},kb:function(a,c){z.push({xi:c,ZK:a});null===v&&null===w&&(w=window.setTimeout(b,100));return!0},call:f,uD:g,B:d,C:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.K&&_.K||(_.K=window.gadgets.rpc,_.K.config=_.K.config,_.K.register=_.K.register,_.K.unregister=_.K.unregister,_.K.Iy=_.K.registerDefault,_.K.jA=_.K.unregisterDefault,_.K.ev=_.K.forceParentVerifiable,_.K.call=_.K.call,_.K.wj=_.K.getRelayUrl,_.K.Te=_.K.setRelayUrl,_.K.Zm=_.K.setAuthToken,_.K.jk=_.K.setupReceiver,_.K.og=_.K.getAuthToken,_.K.jr=_.K.removeReceiver,_.K.Kv=_.K.getRelayChannel,_.K.Sm=_.K.receive,_.K.Ey=_.K.receiveSameDomain,_.K.Aa=
_.K.getOrigin,_.K.Ff=_.K.getTargetOrigin,_.K.Xt=_.K._getTargetWin,_.K.tD=_.K._parseSiblingId);else{_.K=function(){function a(a,b){if(!ca[a]){var c=xa;b||(c=ta);ca[a]=c;for(var d=da[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=G[a];c.call(a,f.f,f)}da[a]=[]}}function b(){function a(){Za=!0}pa||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),pa=!0)}function c(a,c,d,e,f){G[c]&&G[c]===d||(_.Mb("Invalid gadgets.rpc token. "+
G[c]+" vs "+d),Qa(c,2));f.onunload=function(){J[c]&&!Za&&(Qa(c,1),_.K.jr(c))};b();e=(0,_.ec)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(G[b.f]&&G[b.f]!==b.t&&(_.Mb("Invalid gadgets.rpc token. "+G[b.f]+" vs "+b.t),Qa(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.K.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,g;try{g=e(f)}catch(k){}f&&
g==d||(f=c);b.referer=f}d=(x[b.s]||x[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.K.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function g(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==J[a]){"undefined"===typeof J[a]&&(J[a]=0);var c=g(a);".."!==a&&null==c||!0!==xa.kb(a,b)?!0!==J[a]&&10>J[a]++?window.setTimeout(function(){k(a,b)},500):(ca[a]=ta,J[a]=!0):J[a]=!0}}function l(a){(a=y[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));y[a]=b;"undefined"!==typeof c&&(C[a]=!!c)}function n(a,b){b=b||"";G[a]=String(b);k(a,b)}function p(a){a=(a.passReferrer||"").split(":",2);X=a[0]||"none";Aa=a[1]||"origin"}function v(b){"true"===String(b.useLegacyProtocol)&&(xa=ic.lm||ta,xa.Xa(d,a))}function z(a,b){function c(d){d=d&&d.rpc||{};p(d);var f=d.parentRelayUrl||"",f=e(W.parent||b)+f;m("..",f,"true"===String(d.useLegacyProtocol));
v(d);n("..",a)}!W.parent&&b?c({}):_.Wb.register("rpc",null,c)}function w(a,b,c){if(".."===a)z(c||W.rpctoken||W.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.I)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.K.Aa(d);m(a,b);b=_.I.qb(d);n(a,c||b.rpctoken)}}var x={},y={},C={},G={},A=0,H={},J={},W={},ca={},da={},X=null,Aa=null,S=window.top!==window.self,qa=window.name,Qa=function(){},aa=window.console,ia=aa&&aa.log&&function(a){aa.log(a)}||function(){},
ta=function(){function a(b){return function(){ia(b+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.I&&(W=_.I.qb());var Za=!1,pa=!1,xa=function(){if("flash"==W.rpctx)return ic.Al;if("rmr"==W.rpctx)return ic.Ty;var a="function"===typeof window.postMessage?ic.xs:"object"===typeof window.postMessage?ic.xs:window.ActiveXObject?ic.Al?ic.Al:ic.Dx?ic.Dx:ic.lm:0<window.navigator.userAgent.indexOf("WebKit")?
ic.Ty:"Gecko"===window.navigator.product?ic.frameElement:ic.lm;a||(a=ta);return a}();x[""]=function(){ia("Unknown RPC service: "+this.s)};x.__cb=function(a,b){var c=H[a];c&&(delete H[a],c.call(this,b))};return{config:function(a){"function"===typeof a.$y&&(Qa=a.$y)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");x[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete x[a]},Iy:function(a){x[""]=a},jA:function(){delete x[""]},
ev:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=qa:"/"==a.charAt(0)&&(e=_.K.Aa(window.location.href),e="/"+qa+(e?"|"+e:""));++A;c&&(H[A]=c);var g={s:b,f:e,c:c?A:0,a:Array.prototype.slice.call(arguments,3),t:G[a],l:!!C[a]},k;a:if("bidir"===X||"c2p"===X&&".."===a||"p2c"===X&&".."!==a){k=window.location.href;var l="?";if("query"===Aa)l="#";else if("hash"===Aa)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(g.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=
ca[a])||null===f(a)||(k=xa),0===b.indexOf("legacy__")&&(k=xa,g.s=b.substring(8),g.c=g.c?g.c:A),g.g=!0,g.r=e,k?(C[a]&&(k=ic.lm),!1===k.call(a,e,g)&&(ca[a]=ta,xa.call(a,e,g))):da[a]?da[a].push(g):da[a]=[g]},wj:l,Te:m,Zm:n,jk:w,og:function(a){return G[a]},jr:function(a){delete y[a];delete C[a];delete G[a];delete J[a];delete ca[a]},Kv:function(){return xa.Bh()},Sm:function(a,b){4<a.length?xa.uD(a,d):c.apply(null,a.concat(b))},Ey:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},
0)},Aa:e,Ff:function(a){var b=null,c=l(a);c?b=c:(c=f(a))?b=c.origin:b=".."==a?W.parent:window.document.getElementById(a).src;return e(b)},Xa:function(){!1===xa.Xa(d,a)&&(xa=ta);S?w(".."):_.Wb.register("rpc",null,function(a){a=a.rpc||{};p(a);v(a)})},Xt:g,tD:f,A:"__ack",Tn:qa||"..",D:0,C:1,B:2}}();_.K.Xa()};
_.K.config({$y:function(a){throw Error("h`"+a);}});_.Ob=_.Vb;_.D("gadgets.rpc.config",_.K.config);_.D("gadgets.rpc.register",_.K.register);_.D("gadgets.rpc.unregister",_.K.unregister);_.D("gadgets.rpc.registerDefault",_.K.Iy);_.D("gadgets.rpc.unregisterDefault",_.K.jA);_.D("gadgets.rpc.forceParentVerifiable",_.K.ev);_.D("gadgets.rpc.call",_.K.call);_.D("gadgets.rpc.getRelayUrl",_.K.wj);_.D("gadgets.rpc.setRelayUrl",_.K.Te);_.D("gadgets.rpc.setAuthToken",_.K.Zm);_.D("gadgets.rpc.setupReceiver",_.K.jk);_.D("gadgets.rpc.getAuthToken",_.K.og); _.D("gadgets.rpc.removeReceiver",_.K.jr);_.D("gadgets.rpc.getRelayChannel",_.K.Kv);_.D("gadgets.rpc.receive",_.K.Sm);_.D("gadgets.rpc.receiveSameDomain",_.K.Ey);_.D("gadgets.rpc.getOrigin",_.K.Aa);_.D("gadgets.rpc.getTargetOrigin",_.K.Ff);

}catch(e){_._DumpException(e)}
try{
_.I=_.I||{};_.I.Pk=function(a,b,c,d){"undefined"!=typeof a.addEventListener?a.addEventListener(b,c,d):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):_.Nb("cannot attachBrowserEvent: "+b)};_.I.sJ=function(a){var b=window;b.removeEventListener?b.removeEventListener("mousemove",a,!1):b.detachEvent?b.detachEvent("onmousemove",a):_.Nb("cannot removeBrowserEvent: mousemove")};

}catch(e){_._DumpException(e)}
try{
_.lk=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=g,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,n,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),n=1518500249):(m=d^f^k,n=1859775393):60>c?(m=d&f|k&(d|f),n=2400959708):(m=d^f^k,n=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+n+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,g=a.length;e<g;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var g=63;56<=g;g--)f[g]=d&255,d>>>=8;b(f);for(g=d=0;5>g;g++)for(var l=24;0<=l;l-=8)a[d++]=e[g]>>l&255;return a}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,xe:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
_.mk=function(){function a(a){var b=_.lk();b.update(a);return b.xe()}var b=window.crypto;if(b&&"function"==typeof b.getRandomValues)return function(){var a=new window.Uint32Array(1);b.getRandomValues(a);return Number("0."+a[0])};var c=_.E("random/maxObserveMousemove");null==c&&(c=-1);var d=0,e=Math.random(),f=1,g=1E6*(window.screen.width*window.screen.width+window.screen.height),k=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;f=
f*b%g;0<c&&++d==c&&_.I.sJ(k)};0!=c&&_.I.Pk(window,"mousemove",k,!1);var l=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+e);return function(){var b=f,b=b+(0,window.parseInt)(l.substr(0,20),16);l=a(l);return b/(g+Math.pow(16,20))}}();
_.D("shindig.random",_.mk);
}catch(e){_._DumpException(e)}
try{
_.L={};_.Uc={};window.iframer=_.Uc;
}catch(e){_._DumpException(e)}
try{
_.L.ua=_.L.ua||{};_.L.ua.PD=function(a){try{return!!a.document}catch(b){}return!1};_.L.ua.Sv=function(a){var b=a.parent;return a!=b&&_.L.ua.PD(b)?_.L.ua.Sv(b):a};_.L.ua.rU=function(a){var b=a.userAgent||"";a=a.product||"";return 0!=b.indexOf("Opera")&&-1==b.indexOf("WebKit")&&"Gecko"==a&&0<b.indexOf("rv:1.")};

}catch(e){_._DumpException(e)}
try{
var br=function(){_.L.Tw++;return["I",_.L.Tw,"_",(new Date).getTime()].join("")},xr;var cr=function(a){return a instanceof Array?a.join(","):a instanceof Object?(0,_.dc)(a):a};var dr=function(){};var er=function(a){a&&a.match(fr)&&_.ib("googleapis.config/gcv",a)};var gr=function(a){_.hj.oo.vK(a)};var hr=function(a){_.hj.oo.Cr(a)};_.ir=function(a,b){var c=b||{},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c};
_.jr=function(a,b,c,d,e){var f=[],g;for(g in a)if(a.hasOwnProperty(g)){var k=b,l=c,m=a[g],n=d,p=kr(g);p[k]=p[k]||{};n=_.I.Dm(n,m);m._iframe_wrapped_rpc_&&(n._iframe_wrapped_rpc_=!0);p[k][l]=n;f.push(g)}if(e)for(g in _.L.Mh)_.L.Mh.hasOwnProperty(g)&&f.push(g);return f.join(",")};var lr=function(a,b,c){var d={};if(a&&a._methods){a=a._methods.split(",");for(var e=0;e<a.length;e++){var f=a[e];d[f]=mr(f,b,c)}}return d};
var nr=function(a){if(a&&a.disableMultiLevelParentRelay)a=!1;else{var b;if(b=_.Uc&&_.Uc._open&&"inline"!=a.style&&!0!==a.inline)a=a.container,b=!(a&&("string"==typeof a&&window.document.getElementById(a)||window.document==(a.ownerDocument||a.document)));a=b}return a};var or=function(a,b){var c={},d=b.params||{},e;for(e in a)"#"==e.charAt(0)&&(c[e.substring(1)]=a[e]),0==e.indexOf("fr-")&&(c[e.substring(3)]=a[e]),"#"==d[e]&&(c[e]=a[e]);for(var f in c)delete a["fr-"+f],delete a["#"+f],delete a[f];return c};
var pr=function(a){if(":"==a.charAt(0)){var b=_.E("iframes/"+a.substring(1));a={};_.Pa(b,a);(b=a.url)&&(a.url=_.xm(b));a.params||(a.params={});return a}return{url:_.xm(a)}};var qr=function(a){function b(){}b.prototype=rr.prototype;a.prototype=new b};var sr=function(a){return _.L.nk[a]};var tr=function(a,b){_.L.nk[a]=b};var ur=function(a){a=a||{};"auto"===a.height&&(a.height=_.Il.Cb());var b=window&&vr&&vr.ha();b?b.Ry(a.width||0,a.height||0):_.Uc&&_.Uc._resizeMe&&_.Uc._resizeMe(a)};var wr=function(a){er(a)};
xr=function(a){var b=_.Xa(a.location.href,"urlindex");if(b=_.Ha(_.bb,"fUrl",[])[b]){var c=a.location.hash,b=b+(/#/.test(b)?c.replace(/^#/,"&"):c);a.location.replace(b)}};_.yr=function(){return _.Da.location.origin||_.Da.location.protocol+"//"+_.Da.location.host};
if(window.ToolbarApi)vr=window.ToolbarApi,vr.ha=window.ToolbarApi.getInstance,vr.prototype=window.ToolbarApi.prototype,_.h=vr.prototype,_.h.openWindow=vr.prototype.openWindow,_.h.xu=vr.prototype.closeWindow,_.h.Fz=vr.prototype.setOnCloseHandler,_.h.pu=vr.prototype.canClosePopup,_.h.Ry=vr.prototype.resizeWindow;else{var vr=function(){},zr=null;vr.ha=function(){!zr&&window.external&&window.external.GTB_IsToolbar&&(zr=new vr);return zr};_.h=vr.prototype;_.h.openWindow=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.h.xu=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.h.Fz=function(a,b){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,b)};_.h.pu=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.h.Ry=function(a,b){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,b)};window.ToolbarApi=vr;window.ToolbarApi.getInstance=vr.ha};
var Ar=function(){_.K.register("_noop_echo",function(){this.callback(_.L.MF(_.L.Lf[this.f]))})},Br=function(){window.setTimeout(function(){_.K.call("..","_noop_echo",_.L.WI)},0)},mr=function(a,b,c){var d=function(d){var f=Array.prototype.slice.call(arguments,0),g=f[f.length-1];if("function"===typeof g){var k=g;f.pop()}f.unshift(b,a,k,c);_.K.call.apply(_.K,f)};d._iframe_wrapped_rpc_=!0;return d},kr=function(a){_.L.Tm[a]||(_.L.Tm[a]={},_.K.register(a,function(b,c){var d=this.f;if(!("string"!=typeof b||
b in{}||d in{})){var e=this.callback,f=_.L.Tm[a][d],g;f&&Object.hasOwnProperty.call(f,b)?g=f[b]:Object.hasOwnProperty.call(_.L.Mh,a)&&(g=_.L.Mh[a]);if(g)return d=Array.prototype.slice.call(arguments,1),g._iframe_wrapped_rpc_&&e&&d.push(e),g.apply({},d)}_.Mb(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',b,'" from frame "',d,'".'].join(""));return null}));return _.L.Tm[a]};
_.L.MD=function(a,b,c){var d=Array.prototype.slice.call(arguments);_.L.Hv(function(a){a.sameOrigin&&(d.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.K.call.apply(_.K,d))})};_.L.nJ=function(a,b){_.K.register(a,b)};
var fr=/^[-_.0-9A-Za-z]+$/,Cr={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},Dr={onBeforeParentOpen:"beforeparentopen"},Er={onOpen:function(a){var b=a.gb();a.Dd(b.container||b.element);return a},onClose:function(a){a.remove()}};_.L.Fh=function(a){var b=_.Ka();_.Pa(_.lm,b);_.Pa(a,b);return b};
var rr=function(a,b,c,d,e,f,g,k){this.config=pr(a);this.openParams=this.$j=b||{};this.params=c||{};this.methods=d;this.mn=!1;Fr(this,b.style);this.$i={};Gr(this,function(){var a;(a=this.$j.style)&&_.L.nk[a]?a=_.L.nk[a]:a?(_.Nb(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=Er;if(a){var b;if("function"===typeof a)b=a(this);else{var c={};for(b in a){var d=a[b];c[b]="function"===typeof d?_.I.Dm(a,d,this):d}b=c}for(var g in e)a=b[g],"function"===typeof a&&
Hr(this,e[g],_.I.Dm(b,a))}f&&Hr(this,"close",f)});this.of=this.ac=g;this.Qq=(k||[]).slice();g&&this.Qq.unshift(g.da())};rr.prototype.gb=function(){return this.$j};rr.prototype.Ce=function(){return this.params};rr.prototype.Ml=function(){return this.methods};rr.prototype.Db=function(){return this.of};var Fr=function(a,b){if(!a.mn){var c=b&&!_.L.nk[b]&&_.L.Eo[b];c?(a.Do=[],c(function(){a.mn=!0;for(var b=0,c=a.Do.length;b<c;++b)a.Do[b].call(a)})):a.mn=!0}},Gr=function(a,b){a.mn?b.call(a):a.Do.push(b)};
rr.prototype.Jb=function(a,b){Gr(this,function(){Hr(this,a,b)})};var Hr=function(a,b,c){a.$i[b]=a.$i[b]||[];a.$i[b].push(c)};rr.prototype.Og=function(a,b){Gr(this,function(){var c=this.$i[a];if(c)for(var d=0,e=c.length;d<e;++d)if(c[d]===b){c.splice(d,1);break}})};
rr.prototype.ie=function(a,b){var c,d=this.$i[a];if(d)for(var e=Array.prototype.slice.call(arguments,1),f=0,g=d.length;f<g;++f)try{c=d[f].apply({},e)}catch(k){_.Mb(['Exception when calling callback "',a,'" with exception "',k.name,": ",k.message,'".'].join(""))}return c};
var Ir=function(a){return"number"==typeof a?{value:a,np:a+"px"}:"100%"==a?{value:100,np:"100%",lx:!0}:null},Jr=function(a,b,c,d,e,f,g){rr.call(this,a,b,c,d,Cr,e,f,g);this.id=b.id||br();this.B=b.rpctoken&&String(b.rpctoken)||Math.round(1E9*(0,_.mk)());this.D=or(this.params,this.config);this.hp={};Gr(this,function(){this.ie("open");_.ir(this.hp,this)})};qr(Jr);_.h=Jr.prototype;
_.h.Dd=function(a,b){if(!this.config.url)return _.Mb("Cannot open iframe, empty URL."),this;var c=this.id;_.L.Lf[c]=this;var d=_.ir(this.methods);d._ready=this.Lm;d._close=this.close;d._open=this.et;d._resizeMe=this.ft;d._renderstart=this.Rx;var e=this.D;this.B&&(e.rpctoken=this.B);e._methods=_.jr(d,c,"",this,!0);this.C=a="string"===typeof a?window.document.getElementById(a):a;d={};d.id=c;if(b){d.attributes=b;var f=b.style;if("string"===typeof f){var g;if(f){g=[];for(var f=f.split(";"),k=0,l=f.length;k<
l;++k){var m=f[k];if(0!=m.length||k+1!=l)m=m.split(":"),2==m.length&&m[0].match(/^[ a-zA-Z_-]+$/)&&m[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?g.push(m.join(":")):_.Mb(['Iframe style "',f[k],'" not allowed.'].join(""))}g=g.join(";")}else g="";b.style=g}}this.gb().allowPost&&(d.allowPost=!0);d.queryParams=this.params;d.fragmentParams=e;d.paramsSerializer=cr;this.A=_.zm(this.config.url,a,d);e=this.A.getAttribute("data-postorigin")||this.A.src;_.L.Lf[c]=this;_.K.Zm(this.id,this.B);_.K.Te(this.id,e);return this};
_.h.Hc=function(a,b){this.hp[a]=b};_.h.da=function(){return this.id};_.h.Da=function(){return this.A};_.h.Na=function(){return this.C};_.h.Qd=function(a){this.C=a};_.h.Lm=function(a){var b=lr(a,this.id,"");this.of&&"function"==typeof this.methods._ready&&(a._methods=_.jr(b,this.of.da(),this.id,this,!1),this.methods._ready(a));_.ir(a,this);_.ir(b,this);this.ie("ready",a)};_.h.Rx=function(a){this.ie("renderstart",a)};_.h.close=function(a){a=this.ie("close",a);delete _.L.Lf[this.id];return a};
_.h.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.h.et=function(a){var b=lr(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.C);if(nr(a.openParams))new Kr(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain);else{var c=new Jr(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain),d=this;Gr(c,function(){var a={childId:c.da()},f=c.hp;f._toclose=c.close;a._methods=_.jr(f,d.id,c.id,c,!1);b._onopen(a)})}};
_.h.ft=function(a){if(void 0===this.ie("resize",a)&&this.A){var b=Ir(a.width);null!=b&&(this.A.style.width=b.np);a=Ir(a.height);null!=a&&(this.A.style.height=a.np);this.A.parentElement&&(null!=b&&b.lx||null!=a&&a.lx)&&(this.A.parentElement.style.display="block")}};
var Kr=function(a,b,c,d,e,f,g){rr.call(this,a,b,c,d,Dr,e,f,g);this.url=a;this.A=null;this.Zq=br();Gr(this,function(){var a;this.ie("beforeparentopen");var b=_.ir(this.methods);b._onopen=this.RI;b._ready=this.Lm;b._onclose=this.QI;this.params._methods=_.jr(b,"..",this.Zq,this,!0);b={};for(a in this.params)b[a]=cr(this.params[a]);var c=this.config.url;if(this.$j.hideUrlFromParent){a=window.name;var d=c,c=_.em(this.config.url,this.params,{},cr),e=b,b={};b._methods=e._methods;b["#opener"]=e["#opener"];
b["#urlindex"]=e["#urlindex"];b["#opener"]&&void 0!=e["#urlindex"]?(b["#opener"]=a+","+b["#opener"],a=d):(d=_.Ha(_.bb,"fUrl",[]),e=d.length,d[e]=c,_.bb.rUrl=xr,b["#opener"]=a,b["#urlindex"]=e,a=_.hj.Aa(_.Da.location.href),c=_.E("iframes/relay_url_"+(0,window.encodeURIComponent)(a))||"/_/gapi/sibling/1/frame.html",a=a+c);c=a}_.Uc._open({url:c,openParams:this.$j,params:b,proxyId:this.Zq,openedByProxyChain:this.Qq})})};qr(Kr);Kr.prototype.B=function(){return this.A};
Kr.prototype.RI=function(a){this.A=a.childId;var b=lr(a,"..",this.A);_.ir(b,this);this.close=b._toclose;_.L.Lf[this.A]=this;this.of&&this.methods._onopen&&(a._methods=_.jr(b,this.of.da(),this.A,this,!1),this.methods._onopen(a))};Kr.prototype.Lm=function(a){var b=String(this.A),c=lr(a,"..",b);_.ir(a,this);_.ir(c,this);this.ie("ready",a);this.of&&this.methods._ready&&(a._methods=_.jr(c,this.of.da(),b,this,!1),this.methods._ready(a))};
Kr.prototype.QI=function(a){if(this.of&&this.methods._onclose)this.methods._onclose(a);else return a=this.ie("close",a),delete _.L.Lf[this.A],a};
var Mr=function(a,b,c,d,e,f,g){rr.call(this,a,b,c,d,Dr,f,g);this.id=b.id||br();this.B=e;d._close=this.close;this.onClosed=this.A;this.rA=0;Gr(this,function(){this.ie("beforeparentopen");var b=_.ir(this.methods);this.params._methods=_.jr(b,"..",this.Zq,this,!0);b={};b.queryParams=this.params;a=_.qm(_.Ea,this.config.url,this.id,b);var c=e.openWindow(a);this.canAutoClose=function(a){a(e.pu(c))};e.Fz(c,this);this.rA=c})};qr(Mr);Mr.prototype.close=function(a){a=this.ie("close",a);this.B.xu(this.rA);return a};
Mr.prototype.A=function(){this.ie("close")};
(function(){_.L.Lf={};_.L.nk={};_.L.Eo={};_.L.Tw=0;_.L.Tm={};_.L.Mh={};_.L.Nm=null;_.L.Mm=[];_.L.WI=function(a){var b=!1;try{if(null!=a)var e=window.parent.frames[a.id],b=e.iframer.id==a.id&&e.iframes.openedId_(_.Uc.id)}catch(f){}try{_.L.Nm={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:b};for(a=0;a<_.L.Mm.length;++a)_.L.Mm[a](_.L.Nm);_.L.Mm=[]}catch(g){}};_.L.MF=function(a){var b=a&&a.of,e=null;b&&(e={},e.id=b.da(),e.proxyChain=
a.Qq);return e};Ar();if(window.parent!=window){var a=_.I.qb();a.gcv&&er(a.gcv);var b=a.jsh;b&&gr(b);_.ir(lr(a,"..",""),_.Uc);_.ir(a,_.Uc);Br()}_.L.wa=sr;_.L.nb=tr;_.L.uK=wr;_.L.resize=ur;_.L.qF=function(a){return _.L.Eo[a]};_.L.Fr=function(a,b){_.L.Eo[a]=b};_.L.Qy=ur;_.L.GK=wr;_.L.im={};_.L.im.get=sr;_.L.im.set=tr;_.L.AD=function(a,b){kr(a);_.L.Mh[a]=b||window[a]};_.L.WT=function(a){delete _.L.Mh[a]};_.L.open=function(a,b,e,f,g,k){3==arguments.length?f={}:4==arguments.length&&"function"===typeof f&&
(g=f,f={});var l="bubble"===b.style&&vr?vr.ha():null;return l?new Mr(a,b,e,f,l,g,k):nr(b)?new Kr(a,b,e,f,g,k):new Jr(a,b,e,f,g,k)};_.L.close=function(a,b){_.Uc&&_.Uc._close&&_.Uc._close(a,b)};_.L.ready=function(a,b,e){2==arguments.length&&"function"===typeof b&&(e=b,b={});var f=a||{};"height"in f||(f.height=_.Il.Cb());f._methods=_.jr(b||{},"..","",_.Uc,!0);_.Uc&&_.Uc._ready&&_.Uc._ready(f,e)};_.L.Hv=function(a){_.L.Nm?a(_.L.Nm):_.L.Mm.push(a)};_.L.TI=function(a){return!!_.L.Lf[a]};_.L.xF=function(){return["https://ssl.gstatic.com/gb/js/",
_.E("googleapis.config/gcv")].join("")};_.L.Ay=function(a){var b={mouseover:1,mouseout:1};if(_.Uc._event)for(var e=0;e<a.length;e++){var f=a[e];f in b&&_.I.Pk(window.document,f,function(a){_.Uc._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.L.xK=gr;_.L.Cr=hr;_.L.ux=dr;_.L.Yw=_.Uc})();
_.D("iframes.allow",_.L.AD);_.D("iframes.callSiblingOpener",_.L.MD);_.D("iframes.registerForOpenedSibling",_.L.nJ);_.D("iframes.close",_.L.close);_.D("iframes.getGoogleConnectJsUri",_.L.xF);_.D("iframes.getHandler",_.L.wa);_.D("iframes.getDeferredHandler",_.L.qF);_.D("iframes.getParentInfo",_.L.Hv);_.D("iframes.iframer",_.L.Yw);_.D("iframes.open",_.L.open);_.D("iframes.openedId_",_.L.TI);_.D("iframes.propagate",_.L.Ay);_.D("iframes.ready",_.L.ready);_.D("iframes.resize",_.L.resize);
_.D("iframes.setGoogleConnectJsVersion",_.L.uK);_.D("iframes.setBootstrapHint",_.L.Cr);_.D("iframes.setJsHint",_.L.xK);_.D("iframes.setHandler",_.L.nb);_.D("iframes.setDeferredHandler",_.L.Fr);_.D("IframeBase",rr);_.D("IframeBase.prototype.addCallback",rr.prototype.Jb);_.D("IframeBase.prototype.getMethods",rr.prototype.Ml);_.D("IframeBase.prototype.getOpenerIframe",rr.prototype.Db);_.D("IframeBase.prototype.getOpenParams",rr.prototype.gb);_.D("IframeBase.prototype.getParams",rr.prototype.Ce);
_.D("IframeBase.prototype.removeCallback",rr.prototype.Og);_.D("Iframe",Jr);_.D("Iframe.prototype.close",Jr.prototype.close);_.D("Iframe.prototype.exposeMethod",Jr.prototype.Hc);_.D("Iframe.prototype.getId",Jr.prototype.da);_.D("Iframe.prototype.getIframeEl",Jr.prototype.Da);_.D("Iframe.prototype.getSiteEl",Jr.prototype.Na);_.D("Iframe.prototype.openInto",Jr.prototype.Dd);_.D("Iframe.prototype.remove",Jr.prototype.remove);_.D("Iframe.prototype.setSiteEl",Jr.prototype.Qd);
_.D("Iframe.prototype.addCallback",Jr.prototype.Jb);_.D("Iframe.prototype.getMethods",Jr.prototype.Ml);_.D("Iframe.prototype.getOpenerIframe",Jr.prototype.Db);_.D("Iframe.prototype.getOpenParams",Jr.prototype.gb);_.D("Iframe.prototype.getParams",Jr.prototype.Ce);_.D("Iframe.prototype.removeCallback",Jr.prototype.Og);_.D("IframeProxy",Kr);_.D("IframeProxy.prototype.getTargetIframeId",Kr.prototype.B);_.D("IframeProxy.prototype.addCallback",Kr.prototype.Jb);_.D("IframeProxy.prototype.getMethods",Kr.prototype.Ml);
_.D("IframeProxy.prototype.getOpenerIframe",Kr.prototype.Db);_.D("IframeProxy.prototype.getOpenParams",Kr.prototype.gb);_.D("IframeProxy.prototype.getParams",Kr.prototype.Ce);_.D("IframeProxy.prototype.removeCallback",Kr.prototype.Og);_.D("IframeWindow",Mr);_.D("IframeWindow.prototype.close",Mr.prototype.close);_.D("IframeWindow.prototype.onClosed",Mr.prototype.A);_.D("iframes.util.getTopMostAccessibleWindow",_.L.ua.Sv);_.D("iframes.handlers.get",_.L.im.get);_.D("iframes.handlers.set",_.L.im.set); _.D("iframes.resizeMe",_.L.Qy);_.D("iframes.setVersionOverride",_.L.GK);
rr.prototype.send=function(a,b,c){_.L.gz(this,a,b,c)};_.Uc.send=function(a,b,c){_.L.gz(_.Uc,a,b,c)};rr.prototype.register=function(a,b){var c=this;c.Jb(a,function(a){b.call(c,a)})};_.L.gz=function(a,b,c,d){var e=[];void 0!==c&&e.push(c);d&&e.push(function(a){d.call(this,[a])});a[b]&&a[b].apply(a,e)};_.L.Gi=function(){return!0};_.D("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.L.Gi);_.D("IframeBase.prototype.send",rr.prototype.send);_.D("IframeBase.prototype.register",rr.prototype.register);
_.D("Iframe.prototype.send",Jr.prototype.send);_.D("Iframe.prototype.register",Jr.prototype.register);_.D("IframeProxy.prototype.send",Kr.prototype.send);_.D("IframeProxy.prototype.register",Kr.prototype.register);_.D("IframeWindow.prototype.send",Mr.prototype.send);_.D("IframeWindow.prototype.register",Mr.prototype.register);_.D("iframes.iframer.send",_.L.Yw.send);

}catch(e){_._DumpException(e)}
try{
_.kj=window.googleapis&&window.googleapis.server||{};
}catch(e){_._DumpException(e)}
try{
_.I=_.I||{};
(function(){function a(b){var c="";if(3==b.nodeType||4==b.nodeType)c=b.nodeValue;else if(b.innerText)c=b.innerText;else if(b.innerHTML)c=b.innerHTML;else if(b.firstChild){c=[];for(b=b.firstChild;b;b=b.nextSibling)c.push(a(b));c=c.join("")}return c}_.I.createElement=function(a){var c;if(!window.document.body||window.document.body.namespaceURI)try{c=window.document.createElementNS("http://www.w3.org/1999/xhtml",a)}catch(d){}return c||window.document.createElement(a)};_.I.Bo=function(a){var c=_.I.createElement("iframe");
try{var d=["<","iframe"],e=a||{},f;for(f in e)e.hasOwnProperty(f)&&(d.push(" "),d.push(f),d.push('="'),d.push(_.I.wl(e[f])),d.push('"'));d.push("></");d.push("iframe");d.push(">");var g=_.I.createElement(d.join(""));g&&(!c||g.tagName==c.tagName&&g.namespaceURI==c.namespaceURI)&&(c=g)}catch(k){}d=c;a=a||{};for(var l in a)a.hasOwnProperty(l)&&(d[l]=a[l]);return c};_.I.El=function(){if(window.document.body)return window.document.body;try{var a=window.document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml", "body");if(a&&1==a.length)return a[0]}catch(c){}return window.document.documentElement||window.document};_.I.gU=function(b){return a(b)}})();

}catch(e){_._DumpException(e)}
try{
_.wj=function(){return Math.floor((new Date).getTime()/1E3)};var yj,zj;_.xj=function(a,b){this.A=a;var c=b||{};this.D=Number(c.maxAge)||0;this.B=c.domain;this.C=c.path;this.F=!!c.secure};yj=/^[-+/_=.:|%&a-zA-Z0-9@]*$/;zj=/^[A-Z_][A-Z0-9_]{0,63}$/;_.xj.prototype.read=function(){for(var a=this.A+"=",b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c];if(0==d.indexOf(a))return d.substr(a.length)}};
_.xj.prototype.write=function(a,b){if(!zj.test(this.A))throw"Invalid cookie name";if(!yj.test(a))throw"Invalid cookie value";var c=this.A+"="+a;this.B&&(c+=";domain="+this.B);this.C&&(c+=";path="+this.C);var d="number"===typeof b?b:this.D;if(0<=d){var e=new Date;e.setSeconds(e.getSeconds()+d);c+=";expires="+e.toUTCString()}this.F&&(c+=";secure");window.document.cookie=c;return!0};_.xj.prototype.clear=function(){this.write("",0)}; _.xj.iterate=function(a){for(var b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c].split("="),e=d.shift();a(e,d.join("="))}};
var Bj;_.Aj=function(a){this.A=a};Bj={};_.Aj.prototype.read=function(){if(Bj.hasOwnProperty(this.A))return Bj[this.A]};_.Aj.prototype.write=function(a){Bj[this.A]=a;return!0};_.Aj.prototype.clear=function(){delete Bj[this.A]};_.Aj.iterate=function(a){for(var b in Bj)Bj.hasOwnProperty(b)&&a(b,Bj[b])};
var Cj,Dj;Cj=function(){this.A=null;this.key=function(){return null};this.getItem=function(){return this.A};this.setItem=function(a,b){this.A=b;this.length=1};this.removeItem=function(){this.clear()};this.clear=function(){this.A=null;this.length=0};this.length=0};Dj=function(a){try{var b=a||window.sessionStorage;if(!b)return!1;b.setItem("gapi.sessionStorageTest","gapi.sessionStorageTest"+b.length);b.removeItem("gapi.sessionStorageTest");return!0}catch(c){return!1}};
_.Ej=function(a,b){this.B=a;Dj(b)?this.A=b||window.sessionStorage:this.A=new Cj};_.Ej.prototype.read=function(){return this.A.getItem(this.B)};_.Ej.prototype.write=function(a){try{this.A.setItem(this.B,a)}catch(b){return!1}return!0};_.Ej.prototype.clear=function(){this.A.removeItem(this.B)};_.Ej.iterate=function(a){if(Dj())for(var b=0,c=window.sessionStorage.length;b<c;++b){var d=window.sessionStorage.key(b);a(d,window.sessionStorage[d])}};
for(var Fj=0;64>Fj;++Fj);_.Gj="https:"===window.location.protocol;_.Hj=_.Gj||"http:"===window.location.protocol?_.xj:_.Aj;_.Ij=function(a){var b=a.substr(1),c="",d=window.location.hostname;if(""!==b){c=(0,window.parseInt)(b,10);if((0,window.isNaN)(c))return null;b=d.split(".");if(b.length<c-1)return null;b.length==c-1&&(d="."+d)}else d="";return{rb:"S"==a.charAt(0),domain:d,pd:c}};
var Jj;Jj=[".APPS.GOOGLEUSERCONTENT.COM","@DEVELOPER.GSERVICEACCOUNT.COM"];_.Kj=function(a){a=a.toUpperCase();for(var b=0,c=Jj.length;b<c;++b){var d=a.split(Jj[b]);2==d.length&&""===d[1]&&(a=d[0])}a=a.replace(/-/g,"_").toUpperCase();40<a.length&&(b=new _.vj,b.ls(a),a=b.xe().toUpperCase());return a};
_.Lj=function(a){if(0!==a.indexOf("GCSC"))return null;var b={xc:!1};a=a.substr(4);if(!a)return b;var c=a.charAt(0);a=a.substr(1);var d=a.lastIndexOf("_");if(-1==d)return b;var e=_.Ij(a.substr(d+1));if(null==e)return b;a=a.substring(0,d);if("_"!==a.charAt(0))return b;d="E"===c&&e.rb;return!d&&("U"!==c||e.rb)||d&&!_.Gj?b:{xc:!0,rb:d,uu:a.substr(1),domain:e.domain,pd:e.pd}};
var Mj,Nj,Rj,Sj,Vj;Mj=_.Ka();Nj=_.Ka();_.Oj=_.Ka();_.Pj=_.Ka();_.Qj=null;Rj="state code cookie_policy g_user_cookie_policy authuser prompt g-oauth-window status".split(" ");Sj=function(a){this.B=a;this.A=null};Sj.prototype.write=function(a){var b=_.Ka(),c=_.Ka(),d;for(d in a)_.Ma(a,d)&&(c[d]=a[d],b[d]=a[d]);d=0;for(var e=Rj.length;d<e;++d)delete c[Rj[d]];a=String(a.authuser||0);d=_.Ka();d[a]=_.I.qb("#"+_.Tj(c));this.B.write((0,_.dc)(d));this.A=b};Sj.prototype.read=function(){return this.A};
Sj.prototype.clear=function(){this.B.clear();this.A=_.Ka()};
_.Uj=function(a){if(!a)return null;"single_host_origin"!==a&&(a=_.K.Aa(a));var b=window.location.hostname,c=b,d=_.Gj;if("single_host_origin"!==a){c=a.split("://");if(2==c.length)d="https"===c.shift();else return _.Ub("WARNING invalid cookie_policy: "+a),null;c=c[0]}if(-1!==c.indexOf(":"))c=b="";else{a="."+c;if(b.lastIndexOf(a)!==b.length-a.length)return _.Ub("Invalid cookie_policy domain: "+c),null;c=a;b=c.split(".").length-1}return{domain:c,rb:d,pd:b}};
Vj=function(a){if(!a)return null;var b=a.client_id;if(!b)return null;b=_.Kj(b);a=_.Uj(a.cookie_policy);return a?!_.Gj&&a.rb?(_.Ub("WARNING: https cookie_policy set for http domain"),null):["GCSC",a.rb?"E":"U","_",b,"_",a.rb?"S":"H",a.pd].join(""):null};_.Wj=function(a){return a?{domain:a.domain,path:"/",pV:a.rb}:null};_.Xj=function(a){var b=Mj[a];b||(b=new Sj(new _.Aj(a)),Mj[a]=b);return{Rd:b,key:a}};
_.Yj=function(a,b){var c=b?Nj:Mj,d=b?_.Hj:_.Ej,e=a&&Vj(a),f=!!e;a&&!a.g_user_cookie_policy&&(d=_.Aj,e="token");if(!e)if(!b&&_.Qj)e=_.Qj;else return null;var g=c[e];if(!g){g=_.Lj(e);if(!("token"===e||g&&g.xc))return null;g=new d(e,_.Wj(g));b||(g=new Sj(g))}c[e]=g;return{Rd:g,key:e,cF:f}};
_.Zj=function(a,b,c){a=a&&"token"!==a?_.Xj(a):_.Yj();if(!a)return null;if(c){c=a.Rd;_.Ka();var d=c.B.read();c=null;try{c=(0,_.ec)(d)}catch(e){}0==c&&(c=null);d=_.nj()||"0";d=String(d);c=c&&c[d]}else c=a.Rd.read();c&&c.expires_at&&_.wj()>c.expires_at&&(a.Rd.clear(),c=null);c&&c.error&&!b&&(c=null);return c};
_.Tj=function(a){var b="";if(!a)return b;for(var c in a)if({}.hasOwnProperty.call(a,c)){var d;d=a[c];if(null!=d){var e=[(0,window.encodeURIComponent)(c),"="];if(d instanceof Array){for(var f=[],g=0;g<d.length;g++)f.push((0,window.encodeURIComponent)(d[g]));e.push(f.join("+"))}else e.push((0,window.encodeURIComponent)(d));d=e.join("")}else d="";d&&(b&&(b+="&"),b+=d)}return b};_.Ej.iterate(function(a){var b=_.Lj(a);b&&b.xc&&(Mj[a]=new Sj(new _.Ej(a)))}); _.Hj.iterate(function(a){Mj[a]&&(Nj[a]=new _.Hj(a,_.Wj(_.Lj(a))))});

}catch(e){_._DumpException(e)}
try{
_.ak=function(){var a=/\s*;\s*/;return{get:function(b,c){for(var d=b+"=",e=(window.document.cookie||"").split(a),f=0,g;g=e[f];++f)if(0==g.indexOf(d))return g.substr(d.length);return c}}}();
}catch(e){_._DumpException(e)}
try{
var Wc;_.M=function(a,b){return _.ba[a]=b};_.Vc=function(a){var b=_.ja(a);return"array"==b||"object"==b&&"number"==typeof a.length};Wc=0;_.Xc=function(a){return a[_.na]||(a[_.na]=++Wc)};_.Yc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.Zc=function(a){return"function"==_.ja(a)};_.$c=function(a){return"number"==typeof a};
_.ad=function(a,b){return 0==a.lastIndexOf(b,0)};_.bd=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.cd=function(a,b){return Array(b+1).join(a)};_.dd=2147483648*Math.random()|0;_.ed=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
_.fd=Array.prototype;_.gd=_.fd.indexOf?function(a,b,c){return _.fd.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.la(a))return _.la(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.hd=_.fd.lastIndexOf?function(a,b,c){return _.fd.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.la(a))return _.la(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.id=_.fd.forEach?function(a,b,c){_.fd.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.la(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.jd=_.fd.filter?function(a,b,c){return _.fd.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.la(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e};_.kd=_.fd.map?function(a,b,c){return _.fd.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.la(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.ld=_.fd.some?function(a,b,c){return _.fd.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.la(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.md=_.fd.every?function(a,b,c){return _.fd.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.la(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.nd=function(a,b){return 0<=(0,_.gd)(a,b)}; _.od=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Vc(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};

}catch(e){_._DumpException(e)}
try{
var ck,dk;_.bk=function(a){this.A=a};ck=/\s*;\s*/;_.h=_.bk.prototype;_.h.isEnabled=function(){return window.navigator.cookieEnabled};_.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("E`"+a);if(/[;\r\n]/.test(b))throw Error("F`"+b);_.fa(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.va)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+f};
_.h.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(ck),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=_.fa(this.get(a));this.set(a,"",0,b,c);return d};_.h.Zc=function(){return dk(this).keys};_.h.tc=function(){return dk(this).values};_.h.isEmpty=function(){return!this.A.cookie};_.h.Za=function(){return this.A.cookie?(this.A.cookie||"").split(ck).length:0};
_.h.ph=function(a){for(var b=dk(this).values,c=0;c<b.length;c++)if(b[c]==a)return!0;return!1};_.h.clear=function(){for(var a=dk(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};dk=function(a){a=(a.A.cookie||"").split(ck);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};_.ek=new _.bk(window.document);_.ek.B=3950;

}catch(e){_._DumpException(e)}
try{
var fk=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=g,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,n,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),n=1518500249):(m=d^f^k,n=1859775393):60>c?(m=d&f|k&(d|f),n=2400959708):(m=d^f^k,n=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+n+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,g=a.length;e<g;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var g=63;56<=g;g--)f[g]=d&255,d>>>=8;b(f);for(g=d=0;5>g;g++)for(var l=24;0<=l;l-=8)a[d++]=e[g]>>l&255;return a}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,xe:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
var hk,jk,ik;_.gk=function(a){var b={SAPISIDHASH:!0,APISIDHASH:!0};return a&&(a.OriginToken||a.Authorization&&b[String(a.Authorization).split(" ")[0]])?!0:!1};hk=function(){var a=window.__OVERRIDE_SID;null==a&&(a=(new _.bk(window.document)).get("SID"));return!!a};
jk=function(a,b,c){if(1==(_.ka(c)?2:1))return ik([b,a].join(" "));var d=[],e=[];(0,_.id)(c||[],function(a){e.push(a.key);d.push(a.value)});c=(new Date).getTime();var f=[],f=0==d.length?[c,b,a]:[d.join(":"),c,b,a];a=ik(f.join(" "));a=[c,a];0==e.length||a.push(e.join(""));return a.join("_")};ik=function(a){var b=fk();b.update(a);return b.xe().toLowerCase()};
_.kk={pH:_.gk,bI:hk,PF:function(){var a=null;hk()&&(a=window.__PVT,null==a&&(a=_.ak.get("BEAT")));return a},Dl:function(a){var b=_.jj(String(window.location.href));if(hk()){var c=0==b.indexOf("https:")||0==b.indexOf("chrome-extension:"),d=c?window.__SAPISID:window.__APISID;null==d&&(d=(new _.bk(window.document)).get(c?"SAPISID":"APISID"));if(d)return[c?"SAPISIDHASH":"APISIDHASH",jk(b,d,a)].join(" ")}return null}};

}catch(e){_._DumpException(e)}
try{
_.pd=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.rd=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.sd=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};a:{var ud=_.r.navigator;if(ud){var vd=ud.userAgent;if(vd){_.td=vd;break a}}_.td=""}_.wd=function(a){return-1!=_.td.indexOf(a)};_.xd=function(){return _.wd("Trident")||_.wd("MSIE")};
}catch(e){_._DumpException(e)}
try{
var yd,zd,Ad,Bd,Cd,Dd,Ed,Hd,Jd;yd=/&/g;zd=/</g;Ad=/>/g;Bd=/"/g;Cd=/'/g;Dd=/\x00/g;Ed=/[\x00&<>"']/;_.Fd=function(){return _.wd("Opera")||_.wd("OPR")};_.Gd=function(a){if(!Ed.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(yd,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(zd,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ad,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Bd,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Cd,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Dd,"&#0;"));return a};
Hd=function(a,b){return a<b?-1:a>b?1:0};_.Id=function(a,b,c){return 2>=arguments.length?_.fd.slice.call(a,b):_.fd.slice.call(a,b,c)};Jd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
_.Kd=function(a,b){for(var c=0,d=(0,_.bd)(String(a)).split("."),e=(0,_.bd)(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var k=d[g]||"",l=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var p=m.exec(k)||["","",""],v=n.exec(l)||["","",""];if(0==p[0].length&&0==v[0].length)break;c=Hd(0==p[1].length?0:(0,window.parseInt)(p[1],10),0==v[1].length?0:(0,window.parseInt)(v[1],10))||Hd(0==p[2].length,0==v[2].length)||Hd(p[2],v[2])}while(0==c)}return c};
_.Ld=function(a){return null==a?"":String(a)};_.Md=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Jd.length;f++)c=Jd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Nd=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.Od=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Pd=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}; _.Qd=function(){return _.wd("iPhone")&&!_.wd("iPod")&&!_.wd("iPad")};_.Rd=function(){return _.Qd()||_.wd("iPad")||_.wd("iPod")};
var Td,ce,de,je,le;_.Sd=_.Fd();_.N=_.xd();Td=_.wd("Edge");_.Ud=_.wd("Gecko")&&!(-1!=_.td.toLowerCase().indexOf("webkit")&&!_.wd("Edge"))&&!(_.wd("Trident")||_.wd("MSIE"))&&!_.wd("Edge");_.Vd=-1!=_.td.toLowerCase().indexOf("webkit")&&!_.wd("Edge");_.Wd=_.Vd&&_.wd("Mobile");_.Xd=_.wd("Macintosh");_.Yd=_.wd("Windows");_.Zd=_.wd("Linux")||_.wd("CrOS");_.$d=_.wd("Android");_.ae=_.Qd();_.be=_.wd("iPad");
ce=function(){var a=_.td;if(_.Ud)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Td)return/Edge\/([\d\.]+)/.exec(a);if(_.N)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Vd)return/WebKit\/(\S+)/.exec(a)};de=function(){var a=_.r.document;return a?a.documentMode:void 0};_.ee=function(){if(_.Sd&&_.r.opera){var a=_.r.opera.version;return _.Zc(a)?a():a}var a="",b=ce();b&&(a=b?b[1]:"");return _.N&&(b=de(),b>(0,window.parseFloat)(a))?String(b):a}();je={}; _.ke=function(a){return je[a]||(je[a]=0<=_.Kd(_.ee,a))};le=_.r.document;_.me=le&&_.N?de()||("CSS1Compat"==le.compatMode?(0,window.parseInt)(_.ee,10):5):void 0;

}catch(e){_._DumpException(e)}
try{
var zh,Bh,Ch;_.yh=function(a){return/^[\s\xa0]*$/.test(a)};zh=function(a){return Array.prototype.join.call(arguments,"")};_.Ah=function(a){return(0,window.encodeURIComponent)(String(a))};Bh=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.Dh=function(a){if(Ch){Ch=!1;var b=_.r.location;if(b){var c=b.href;if(c&&(c=(c=_.Dh(c)[3]||null)?(0,window.decodeURI)(c):c)&&c!=b.hostname)throw Ch=!0,Error();}}return a.match(Bh)};Ch=_.Vd;
_.Eh=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};_.Fh=function(a,b,c){if(_.ka(b))for(var d=0;d<b.length;d++)_.Fh(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",_.Ah(b))};_.Gh=function(a,b){for(var c in b)_.Fh(c,b[c],a);return a};_.Hh=function(a,b){_.Pd(a,"/")&&(a=a.substr(0,a.length-1));_.ad(b,"/")&&(b=b.substr(1));return zh(a,"/",b)};

}catch(e){_._DumpException(e)}
try{
var nk,ok;nk=function(a){return _.yh(_.Ld(a))};ok=function(a,b){var c=_.I.Bo({id:a,name:a});c.style.width="1px";c.style.height="1px";c.style.position="absolute";c.style.top="-100px";var d;if(window.navigator){d=window.navigator.userAgent||"";var e=window.navigator.product||"";d=0!=d.indexOf("Opera")&&-1==d.indexOf("WebKit")&&"Gecko"==e&&0<d.indexOf("rv:1.")}else d=!1;c.src=d?"about:blank":b;c.tabIndex="-1";window.document.body.appendChild(c);d&&(c.src=b);return c};
_.pk=function(){function a(){return!!m("auth/useFirstPartyAuthV2")}function b(a,b,c,d){var e=m("proxy");if(c||!e)var e=m("root"),f=m("root-1p")||e,g=m("xd3"),e=(c||String(b?f:e))+g;(b=_.I.qb().jsh||_.hj.oo.yv())&&(e+=(0<=e.indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(b));m("push")&&(e+=(0<=e.indexOf("?")?"&":"?")+"p=1");e+="#parent="+(0,window.encodeURIComponent)(null!=d?String(d):_.hj.Aa(window.document.location.href));return e+("&rpctoken="+a)}function c(a,b,c,d){var f=e(c,d);p[f]||
(c=ok(f,b),_.K.register("ready:"+a,function(){_.K.unregister("ready:"+a);if(!v[f]){v[f]=!0;var b=z[f];z[f]=[];for(var c=0,d=b.length;c<d;++c){var e=b[c];k(e.Rg,e.zJ,e.Lb)}}}),_.K.jk(f,b),p[f]=c)}function d(a,d){var e=String(2147483647*(0,_.mk)()|0),f=b(e,a,d);_.gc(function(){c(e,f,a,d)})}function e(a,c){var d=b("",a,c,""),e=n[d];if(!e){e=_.lk();e.update(d);var e=e.xe().toLowerCase(),f=Math.random(),e=e+f;n[d]=e}return"apiproxy"+e}function f(a){if(!a)return null;var b={},c=a.headers||{},d;for(d in c)({}).hasOwnProperty.call(c,
d)&&(b[d]=c[d]);b["Content-Type"]="application/json";return[{key:"gapiRequest",params:{id:"gapiRequest",key:"gapiRequest",httpMethod:"POST",root:a.root,url:"/rpc",urlParams:a.urlParams,headers:b,clientName:a.clientName||null,clientVersion:a.clientVersion||null,body:a.requests||[]}}]}function g(a){return function(b){b=b.gapiRequest.data.body;var c=(0,_.ec)(b);if(c){for(var d={},e=0,f=c.length;e<f;++e)d[c[e].id]=c[e];a(d,b)}else a(c,b)}}function k(a,b,c){var k=void 0,m=!1;if("makeRequest"!==a&&"makeHttpRequests"!==
a)throw'only "makeRequest" and "makeHttpRequests" RPCs are implemented';"makeRequest"===a&&(a="makeHttpRequests",b=f(b),c=g(c));var n=function(a){if(a){if("undefined"!=typeof k&&"undefined"!=typeof a.root&&k!=a.root)throw"all requests in a batch must have the same root URL";k=a.root||k;m=_.kk.pH(a.headers)}};if(b){for(var H=_.E("client/jsonpOverride"),J=0,W=b.length;J<W;++J){var ca=b[J];ca&&(ca=ca.params,n(ca),H&&l(ca,c))}if(H)return}var da=e(m,k);p[da]||d(m,k);v[da]?_.K.call(da,a,function(a){if(this.f==
da&&this.t==_.K.og(this.f)&&this.origin==_.K.Ff(this.f)){var b=(0,_.ec)(a);c(b,a)}},b):(z[da]||(z[da]=[]),z[da].push({Rg:a,zJ:b,Lb:c}))}function l(a,b){if("GET"!=a.httpMethod)throw"JSONP supports GET methods only.";var c="jpcb"+String(2147483647*(0,_.mk)()|0),d=window.document.createElement("script"),e=window.document.getElementsByTagName("head")[0];window[c]=function(a){b(a);try{delete window[c]}catch(f){window[c]=void 0}window.setTimeout(function(){e.removeChild(d)},1)};var f=a.root||m("root"),
g=a.urlParams;g.callback=c;f=_.Hh(f,a.url);g=_.Eh(_.Gh([f],g));d.setAttribute("id",c);d.setAttribute("src",g);d.setAttribute("charset","utf-8");e.appendChild(d)}function m(a){return _.E("googleapis.config/"+a)}var n={},p={},v={},z={};return{Lk:function(b,c,d){var e=d||"auto";b=b||{};if("none"==e)return b;c=c||window.location.href;d=b.Authorization;var f=b.OriginToken;if(!d&&!f){f=_.Zj(void 0,void 0);!f&&window.gapi.auth2&&"function"==typeof window.gapi.auth2._gt&&(f=window.gapi.auth2._gt());f&&f.access_token&&
("oauth2"==e||"auto"==e)&&(d=String(f.token_type||"Bearer")+" "+f.access_token);if(f=!d)f=(!!m("auth/useFirstPartyAuth")||"1p"==e)&&"oauth2"!=e;if(f&&_.kk.bI()){if(a()){d=m("primaryEmail");var e=m("appDomain"),f=m("fogId"),g=[];d&&g.push({key:"e",value:d});e&&g.push({key:"a",value:e});f&&g.push({key:"u",value:f});d=_.kk.Dl(g)}else d=_.kk.Dl();d&&(c=_.google.Hp(c),c=b["X-Goog-AuthUser"]||c,nk(c)&&(!a()||a()&&nk(m("primaryEmail"))&&nk(m("appDomain"))&&nk(m("fogId")))&&(c="0"),nk(c)||(b["X-Goog-AuthUser"]= c))}d?b.Authorization=d:!1!==m("auth/useOriginToken")&&(f=_.kk.PF())&&(b.OriginToken=f)}return b},A:l,Tf:k}}();

}catch(e){_._DumpException(e)}
try{
_.oc=window.tamings___||[];_.pc=window.caja___;_.___=window.___;
}catch(e){_._DumpException(e)}
try{
_.Ba.Zj=function(){var a={},b=[],c=function(a){var b={method:a.request.method,id:a.key};a.request.rpc&&(b.params=a.request.rpc);return b};a.execute=function(a){for(var e={},f={},g=0,k=[],l=0;l<b.length;l++){var m=b[l].request.transport;f[m.name]||(k.push(m),g++);f[m.name]=f[m.name]||[];f[m.name].push(c(b[l]))}l=function(c){c.error&&(e.error=c.error);for(var f=0;f<b.length;f++){var k=b[f].key,l=c[k];l&&(e[k]=l.error?l:l.data||l.result)}g--;0===g&&a(e)};for(m=0;m<k.length;m++)k[m].execute(f[k[m].name], l);0==g&&window.setTimeout(function(){a(e)},0)};a.add=function(c,e){e&&c&&b.push({key:c,request:e});return a};return a};
_.Ba.Jk=function(a,b){if("newBatch"!==a){for(var c=a.split("."),d=window.osapi,e=0;e<c.length-1;e++)d[c[e]]=d[c[e]]||{},d=d[c[e]];var f=c[c.length-1];d[f]?(d.__dupwarn||_.Nb("Skipping duplicate osapi method definition "+a+" on transport "+b.name+"; others may exist, but suppressing warnings"),d.__dupwarn=!0):(d[f]=function(c){c=c||{};c.userId=c.userId||"@viewer";c.groupId=c.groupId||"@self";return new qc(a,b,c)},"undefined"!==typeof _.oc&&_.oc.push(function(){_.pc.markTameAsFunction(d[f],a)}))}};
var qc=function(a,b,c){this.method=a;this.transport=b;this.rpc=c};qc.prototype.execute=function(a){var b="undefined"!==typeof _.pc&&_.pc.getUseless&&_.pc.getUseless(),c=b?_.pc.getUseless():this,d=b?_.pc.untame(a):a;a=_.Ba.Zj();a.add(this.method,this);a.execute(function(a){a.error?d.call(c,a.error):d.call(c,a[c.method])})};
_.D("osapi.newBatch.add",_.Ba.Zj.add);_.D("osapi.newBatch.execute",_.Ba.Zj.execute);_.D("osapi._registerMethod",_.Ba.Jk);_.D("osapi._BoundCall",qc);_.D("osapi._BoundCall.prototype.execute",qc.prototype.execute);
}catch(e){_._DumpException(e)}
try{
var qk=function(a){a=a.split(".");for(var b=window.osapi||window,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b},rk=function(a,b){var c=a.split("."),d=window;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b};
var tk,vk,yk,zk,Ak,uk,Bk,Ck;tk={};vk=function(a,b){_.Ba.Jk(a,{name:"googleapis",execute:uk,root:b});var c=qk(a);rk(a,c);if(0!=a.indexOf("googleapis.")){var d=a.substring(a.indexOf(".")+1),e=d.lastIndexOf(".delete");-1!=e&&e+7==d.length&&(d=d.replace(".delete",".remove"));rk("googleapis."+d,c)}};_.wk=function(a){for(var b in a)a.hasOwnProperty(b)&&(tk[b]=a[b])};_.xk=function(a){null==a?_.sk&&delete _.sk.key:(_.sk=_.sk||{},_.sk.key=a)};
yk=function(a,b){if("trace"!=a)throw'only the "trace" parameter may be set using this API';null==b?_.sk&&delete _.sk[a]:(_.sk=_.sk||{},_.sk[a]=b)};zk=function(a){a=a||{};if(window.navigator){for(var b=["appVersion","platform","userAgent"],c=[],d=0;d<b.length;d++)window.navigator[b[d]]&&c.push((0,window.encodeURIComponent)(b[d])+"="+(0,window.encodeURIComponent)(window.navigator[b[d]]));a["X-ClientDetails"]=c.join("&")}return a};Ak=function(a){a.clientVersion="1.0.0-alpha";_.sk&&(a.urlParams=_.sk)};
uk=function(a,b){for(var c=this.root||null,d=0;d<a.length;d++){var e=a[d],f;f=e.method;f=f.substring(0,f.indexOf("."));e.jsonrpc="2.0";e.key=e.id;c=e.root||c;(f=tk[f]||"v1",!e.apiVersion)&&(e.apiVersion=f)}d={};d=_.pk.Lk(d);d=zk(d);c={requests:a,headers:d,root:c};Ak(c);_.pk.Tf("makeRequest",c,b)};Bk=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];e.key=e.id;var f=e.params.headers||{},f=_.pk.Lk(f),f=zk(f);e.params.headers=f;Ak(e.params)}_.pk.Tf("makeHttpRequests",a,b)};
Ck=function(){var a=_.I.qb(),b={debug:"googleapis.config/debug"},c;for(c in b)a[c]&&_.ib(b[c],"true"==a[c]);for(var d in _.E("googleapis.config/methods"))vk(d);_.E("googleapis.config/versions")&&_.wk(_.E("googleapis.config/versions"));_.E("googleapis.config/developerKey")&&_.xk(_.E("googleapis.config/developerKey"));_.Ba.Jk("googleapis.newHttpRequest",{name:"googleapis",execute:Bk});rk("googleapis.newHttpRequest",qk("googleapis.newHttpRequest"))};Ck();
var Dk=function(){this.A={};this.B=_.Ba.Zj()};Dk.prototype.add=function(a,b,c){this.A[a]=c;this.B.add(a,b);return this};Dk.prototype.execute=function(a){var b=this;this.B.execute(function(c){var d={},e=!1,f;for(f in c)if(c.hasOwnProperty(f)){var g=c[f],k=b.A[f];k?k(g):(d[f]=g,e=!0)}e&&a&&a(d)})};
_.D("googleapis.ApiClient.register",vk);_.D("googleapis.ApiClient.setVersions",_.wk);_.D("googleapis.ApiClient.setDeveloperKey",_.xk);_.D("googleapis.ApiClient.setUrlParameter",yk);_.D("googleapis.ApiClient.init",Ck);_.D("googleapis.Batch",Dk);_.D("googleapis.Batch.prototype.add",Dk.prototype.add);_.D("googleapis.Batch.prototype.execute",Dk.prototype.execute);_.D("googleapis.init",function(){Ck()});_.D("googleapis.newBatch",function(){return new Dk});
_.D("googleapis.newRequest",function(a,b,c){b=b||{};var d={name:"googleapis",execute:uk,root:c},e=_.Ba.Zj(),f=this;c={};c.method=a;c.transport=d;c.rpc=b;c.execute=function(c){e.add(a,{method:a,rpc:b,transport:d});e.execute(function(b){b.error?c.call(f,b.error):c.call(f,b[a])})};return c});_.D("googleapis.register",function(a,b){vk(a,b)});_.D("googleapis.setUrlParameter",function(a,b){yk(a,b)});_.D("googleapis.setDeveloperKey",function(a){_.xk(a)});_.D("googleapis.setVersions",function(a){_.wk(a)});

}catch(e){_._DumpException(e)}
})(this._);
// Google Inc.
