test: &default

  # Credentials for New APIs
  client_id: AR0CiBDB41Bd0AioC1FqW0mlVNcuGiQIZEOYqr_ueyp0AVTziwzg5XOGmvBf
  client_secret: ED_1cRA9v5ehsoD2aLZAn7UENoe3FEmkPoDg447S0dDeCumVva86Ea_-Y73I

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  username: simon.king65-facilitator_api1.gmail.com
  password: MLP7C4HCMZTT6A7Y
  signature: AcbkD2jLSn.hCPB3rhfsE5wX8zSMAvxbibNzxPzROTihhXQOhWvagcfE
  app_id: APP-80W284485P519543T
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: simon.king65@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  
   # Credentials for New APIs
  client_id: Aa0YqBD2feLYrhNgoZSHvawGnGA42jJEq_3YFjzNywCkehfA1Je3_PhKMNys
  client_secret: EBwlGBA7EM6Um3jo8gLqy6PU6bG7Ttut0FZJ8yba3biXKAW5DxNDstP7JKvw

  # Mode can be 'live' or 'sandbox'
  mode: live

  # Credentials for Classic APIs
  username: simon.king65-facilitator_api1.gmail.com
  password: MLP7C4HCMZTT6A7Y
  signature: AcbkD2jLSn.hCPB3rhfsE5wX8zSMAvxbibNzxPzROTihhXQOhWvagcfE
  app_id: APP-80W284485P519543T
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: simon.king65@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  #mode: live

